# Site settings
title: The Cache Clear
email: team@thecacheclear.com
description: > # this means to ignore newlines until "baseurl:"
  The CacheClear is the regular download of things on our minds.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thecacheclearcom" # the base hostname & protocol for your site
twitter_username: cacheclear
github_username:  thecacheclear

# Build settings
markdown: kramdown
